-- Insert mock data for intake_forms table
-- This will populate the table with sample data for testing the admin dashboard

-- Mock Intake Form 1: Emma Rodriguez (High Urgency)
INSERT INTO intake_forms (
  child_name,
  date_of_birth,
  sponsor_id,
  guardian1_name,
  guardian1_email,
  guardian1_address,
  guardian1_cell_phone,
  guardian1_relationship,
  guardian2_name,
  guardian2_email,
  guardian2_cell_phone,
  guardian2_relationship,
  household_members,
  physician_name,
  physician_phone,
  allergies,
  current_medical_conditions,
  school_name,
  school_phone,
  has_iep,
  grade_level,
  diagnosis,
  diagnosing_provider,
  current_medications,
  primary_concerns,
  therapy_goals,
  urgency_assessment,
  pregnancy_complications,
  birth_weight,
  motor_skills_rating,
  language_skills_rating,
  social_skills_rating,
  cognitive_skills_rating,
  play_skills_preferences,
  repetitive_behaviors,
  previous_therapy_experience,
  insurance_coverage,
  preferred_days,
  preferred_time_slot,
  status,
  notes
) VALUES (
  'Emma Rodriguez',
  '2018-03-15',
  'SP001',
  'Maria Rodriguez',
  'maria.rodriguez@email.com',
  '123 Main Street, Aruba',
  '+297-592-0662',
  'Mother',
  'Carlos Rodriguez',
  'carlos.rodriguez@email.com',
  '+297-592-0663',
  'Father',
  ARRAY['Maria Rodriguez', 'Carlos Rodriguez', 'Emma Rodriguez', 'Luna (dog)'],
  'Dr. Sarah Johnson',
  '+297-592-1000',
  'Peanuts, tree nuts',
  'ADHD, mild anxiety',
  'Aruba Elementary School',
  '+297-592-2000',
  true,
  'Kindergarten',
  'ADHD, Autism Spectrum Disorder',
  'Dr. Michael Wilson',
  'Ritalin 10mg daily',
  ARRAY['Attention difficulties', 'Social interaction challenges', 'Communication delays'],
  'Improve focus and attention span, develop social skills, enhance communication abilities',
  'high',
  'Gestational diabetes, premature birth at 35 weeks',
  '2.1 kg',
  3,
  2,
  2,
  3,
  'Building blocks, drawing, pretend play',
  'Hand flapping when excited, lining up toys',
  '6 months of speech therapy, 3 months of occupational therapy',
  true,
  ARRAY['Monday', 'Wednesday', 'Friday'],
  '10:00 - 10:45 am',
  'pending',
  'Emma shows great potential but needs structured support for learning and social development.'
);

-- Mock Intake Form 2: Michael Chen (Moderate Urgency)
INSERT INTO intake_forms (
  child_name,
  date_of_birth,
  sponsor_id,
  guardian1_name,
  guardian1_email,
  guardian1_address,
  guardian1_cell_phone,
  guardian1_relationship,
  guardian2_name,
  guardian2_email,
  guardian2_cell_phone,
  guardian2_relationship,
  household_members,
  physician_name,
  physician_phone,
  allergies,
  current_medical_conditions,
  school_name,
  school_phone,
  has_iep,
  grade_level,
  diagnosis,
  diagnosing_provider,
  current_medications,
  primary_concerns,
  therapy_goals,
  urgency_assessment,
  pregnancy_complications,
  birth_weight,
  motor_skills_rating,
  language_skills_rating,
  social_skills_rating,
  cognitive_skills_rating,
  play_skills_preferences,
  repetitive_behaviors,
  previous_therapy_experience,
  insurance_coverage,
  preferred_days,
  preferred_time_slot,
  status,
  notes
) VALUES (
  'Michael Chen',
  '2019-07-22',
  'SP002',
  'Jennifer Chen',
  'jennifer.chen@email.com',
  '456 Oak Avenue, Aruba',
  '+297-592-0664',
  'Mother',
  'David Chen',
  'david.chen@email.com',
  '+297-592-0665',
  'Father',
  ARRAY['Jennifer Chen', 'David Chen', 'Michael Chen', 'Sophie (cat)'],
  'Dr. Emily Smith',
  '+297-592-1001',
  'Dairy products',
  'Sensory processing disorder',
  'Aruba Primary School',
  '+297-592-2001',
  false,
  'Pre-K',
  'Sensory Processing Disorder',
  'Dr. Lisa Brown',
  'None currently',
  ARRAY['Sensory sensitivities', 'Motor coordination difficulties', 'Emotional regulation'],
  'Develop sensory integration skills, improve motor coordination, enhance emotional regulation',
  'moderate',
  'None',
  '3.2 kg',
  2,
  4,
  3,
  4,
  'Puzzles, sensory bins, outdoor play',
  'Rocking when overwhelmed, touching surfaces repeatedly',
  '3 months of occupational therapy',
  false,
  ARRAY['Tuesday', 'Thursday'],
  '3:30 - 4:15 pm',
  'reviewed',
  'Michael is a bright child who needs support with sensory integration and motor skills development.'
);

-- Mock Intake Form 3: Isabella Garcia (Low Urgency)
INSERT INTO intake_forms (
  child_name,
  date_of_birth,
  sponsor_id,
  guardian1_name,
  guardian1_email,
  guardian1_address,
  guardian1_cell_phone,
  guardian1_relationship,
  guardian2_name,
  guardian2_email,
  guardian2_cell_phone,
  guardian2_relationship,
  household_members,
  physician_name,
  physician_phone,
  allergies,
  current_medical_conditions,
  school_name,
  school_phone,
  has_iep,
  grade_level,
  diagnosis,
  diagnosing_provider,
  current_medications,
  primary_concerns,
  therapy_goals,
  urgency_assessment,
  pregnancy_complications,
  birth_weight,
  motor_skills_rating,
  language_skills_rating,
  social_skills_rating,
  cognitive_skills_rating,
  play_skills_preferences,
  repetitive_behaviors,
  previous_therapy_experience,
  insurance_coverage,
  preferred_days,
  preferred_time_slot,
  status,
  notes
) VALUES (
  'Isabella Garcia',
  '2017-11-08',
  'SP003',
  'Ana Garcia',
  'ana.garcia@email.com',
  '789 Pine Street, Aruba',
  '+297-592-0666',
  'Mother',
  'Roberto Garcia',
  'roberto.garcia@email.com',
  '+297-592-0667',
  'Father',
  ARRAY['Ana Garcia', 'Roberto Garcia', 'Isabella Garcia', 'Diego (brother, age 5)'],
  'Dr. James Wilson',
  '+297-592-1002',
  'None known',
  'Mild speech delay',
  'Aruba Elementary School',
  '+297-592-2002',
  true,
  '1st Grade',
  'Speech and Language Delay',
  'Dr. Sarah Johnson',
  'None',
  ARRAY['Speech articulation', 'Language comprehension', 'Social communication'],
  'Improve speech clarity, enhance language understanding, develop better communication skills',
  'low',
  'None',
  '3.5 kg',
  4,
  2,
  4,
  4,
  'Reading, arts and crafts, group games',
  'Minor hand gestures when speaking',
  '1 year of speech therapy',
  true,
  ARRAY['Monday', 'Wednesday'],
  '4:30 - 5:15 pm',
  'approved',
  'Isabella is making good progress with speech therapy and shows strong potential for continued improvement.'
);

-- Mock Intake Form 4: Lucas Thompson (Immediate Urgency)
INSERT INTO intake_forms (
  child_name,
  date_of_birth,
  sponsor_id,
  guardian1_name,
  guardian1_email,
  guardian1_address,
  guardian1_cell_phone,
  guardian1_relationship,
  guardian2_name,
  guardian2_email,
  guardian2_cell_phone,
  guardian2_relationship,
  household_members,
  physician_name,
  physician_phone,
  allergies,
  current_medical_conditions,
  school_name,
  school_phone,
  has_iep,
  grade_level,
  diagnosis,
  diagnosing_provider,
  current_medications,
  primary_concerns,
  therapy_goals,
  urgency_assessment,
  pregnancy_complications,
  birth_weight,
  motor_skills_rating,
  language_skills_rating,
  social_skills_rating,
  cognitive_skills_rating,
  play_skills_preferences,
  repetitive_behaviors,
  previous_therapy_experience,
  insurance_coverage,
  preferred_days,
  preferred_time_slot,
  status,
  notes
) VALUES (
  'Lucas Thompson',
  '2020-01-30',
  'SP004',
  'Rachel Thompson',
  'rachel.thompson@email.com',
  '321 Elm Court, Aruba',
  '+297-592-0668',
  'Mother',
  'Thomas Thompson',
  'thomas.thompson@email.com',
  '+297-592-0669',
  'Father',
  ARRAY['Rachel Thompson', 'Thomas Thompson', 'Lucas Thompson'],
  'Dr. Amanda Davis',
  '+297-592-1003',
  'Eggs, shellfish',
  'Severe behavioral challenges, possible ODD',
  'Aruba Early Learning Center',
  '+297-592-2003',
  true,
  'Pre-K',
  'Oppositional Defiant Disorder, possible Autism',
  'Dr. Robert Martinez',
  'Guanfacine 1mg daily',
  ARRAY['Aggressive behavior', 'Severe tantrums', 'Difficulty following instructions', 'Safety concerns'],
  'Reduce aggressive behaviors, develop coping strategies, improve compliance and safety',
  'immediate',
  'Preeclampsia, emergency C-section',
  '2.8 kg',
  3,
  1,
  1,
  2,
  'Solitary play, cause-and-effect toys',
  'Intense tantrums, aggressive outbursts, property destruction',
  '6 months of behavioral therapy, 3 months of family counseling',
  true,
  ARRAY['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  '8:30 - 9:45 am',
  'pending',
  'URGENT: Lucas requires immediate intervention due to safety concerns and severe behavioral challenges. Family is struggling to manage behaviors at home.'
);

-- Mock Intake Form 5: Sofia Patel (High Urgency)
INSERT INTO intake_forms (
  child_name,
  date_of_birth,
  sponsor_id,
  guardian1_name,
  guardian1_email,
  guardian1_address,
  guardian1_cell_phone,
  guardian1_relationship,
  guardian2_name,
  guardian2_email,
  guardian2_cell_phone,
  guardian2_relationship,
  household_members,
  physician_name,
  physician_phone,
  allergies,
  current_medical_conditions,
  school_name,
  school_phone,
  has_iep,
  grade_level,
  diagnosis,
  diagnosing_provider,
  current_medications,
  primary_concerns,
  therapy_goals,
  urgency_assessment,
  pregnancy_complications,
  birth_weight,
  motor_skills_rating,
  language_skills_rating,
  social_skills_rating,
  cognitive_skills_rating,
  play_skills_preferences,
  repetitive_behaviors,
  previous_therapy_experience,
  insurance_coverage,
  preferred_days,
  preferred_time_slot,
  status,
  notes
) VALUES (
  'Sofia Patel',
  '2018-09-14',
  'SP005',
  'Priya Patel',
  'priya.patel@email.com',
  '654 Maple Drive, Aruba',
  '+297-592-0670',
  'Mother',
  'Raj Patel',
  'raj.patel@email.com',
  '+297-592-0671',
  'Father',
  ARRAY['Priya Patel', 'Raj Patel', 'Sofia Patel', 'Arjun (brother, age 7)'],
  'Dr. Christopher Lee',
  '+297-592-1004',
  'Latex, dust mites',
  'Asthma, anxiety disorder',
  'Aruba Elementary School',
  '+297-592-2004',
  true,
  'Kindergarten',
  'Anxiety Disorder, Asthma',
  'Dr. Maria Rodriguez',
  'Albuterol inhaler, Fluticasone nasal spray',
  ARRAY['Severe anxiety', 'Social withdrawal', 'Difficulty with transitions', 'Asthma management'],
  'Reduce anxiety symptoms, develop coping strategies, improve social engagement, manage asthma effectively',
  'high',
  'Gestational hypertension',
  '2.9 kg',
  4,
  3,
  2,
  4,
  'Quiet activities, reading, drawing',
  'Nail biting, hair twirling when anxious',
  '1 year of play therapy, 6 months of anxiety treatment',
  true,
  ARRAY['Tuesday', 'Thursday', 'Friday'],
  '11:00 - 11:45 am',
  'reviewed',
  'Sofia is a bright child who struggles with anxiety and social situations. She has shown improvement with therapy but needs continued support.'
);

-- Update the created_at timestamps to be more realistic (different dates)
UPDATE intake_forms SET created_at = '2024-01-15 09:30:00+00' WHERE child_name = 'Emma Rodriguez';
UPDATE intake_forms SET created_at = '2024-01-18 14:15:00+00' WHERE child_name = 'Michael Chen';
UPDATE intake_forms SET created_at = '2024-01-20 11:45:00+00' WHERE child_name = 'Isabella Garcia';
UPDATE intake_forms SET created_at = '2024-01-22 16:20:00+00' WHERE child_name = 'Lucas Thompson';
UPDATE intake_forms SET created_at = '2024-01-25 10:00:00+00' WHERE child_name = 'Sofia Patel';

-- Update some statuses to show different workflow states
UPDATE intake_forms SET status = 'approved' WHERE child_name = 'Isabella Garcia';
UPDATE intake_forms SET status = 'reviewed' WHERE child_name = 'Michael Chen';
UPDATE intake_forms SET status = 'reviewed' WHERE child_name = 'Sofia Patel';
UPDATE intake_forms SET status = 'pending' WHERE child_name = 'Emma Rodriguez';
UPDATE intake_forms SET status = 'pending' WHERE child_name = 'Lucas Thompson';

-- Add some additional metadata
UPDATE intake_forms SET 
  submitted_by = 'Dr. Sarah Johnson',
  contact_email = 'brightefuturearuba@gmail.com',
  contact_phone = '+297-592-0662'
WHERE child_name = 'Emma Rodriguez';

UPDATE intake_forms SET 
  submitted_by = 'Dr. Emily Smith',
  contact_email = 'brightefuturearuba@gmail.com',
  contact_phone = '+297-592-0662'
WHERE child_name = 'Michael Chen';

UPDATE intake_forms SET 
  submitted_by = 'Dr. James Wilson',
  contact_email = 'brightefuturearuba@gmail.com',
  contact_phone = '+297-592-0662'
WHERE child_name = 'Isabella Garcia';

UPDATE intake_forms SET 
  submitted_by = 'Dr. Amanda Davis',
  contact_email = 'brightefuturearuba@gmail.com',
  contact_phone = '+297-592-0662'
WHERE child_name = 'Lucas Thompson';

UPDATE intake_forms SET 
  submitted_by = 'Dr. Christopher Lee',
  contact_email = 'brightefuturearuba@gmail.com',
  contact_phone = '+297-592-0662'
WHERE child_name = 'Sofia Patel';
